# Generated by Django 4.1 on 2023-01-26 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL)),
                ('hashtags', models.ManyToManyField(blank=True, related_name='Post_Hashtags', to='hashtags.hashtag')),
                ('likes', models.ManyToManyField(blank=True, related_name='Post_Likes', to=settings.AUTH_USER_MODEL)),
                ('usertag', models.ManyToManyField(blank=True, related_name='Post_Tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
