# Generated by Django 4.1 on 2023-01-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='usertag',
            new_name='usertags',
        ),
    ]
